#!/usr/bin/env python3

import argparse
import logging
import subprocess
import sys

from argo_config import ArgoConfig

logger = logging.getLogger(__name__)


def run_ingest(
    config: ArgoConfig,
    tenant_name: str,
    tenant_ams_token: str,
    dry_run: bool,
    verify: str,
):
    """Function that composes the appropriate cli command to submit an ingest job execution in flink"""

    cmd = [
        config.flink_path,
        "run",
        "--detached",
        "-c",
        "argo.streaming.AmsIngestMetric",
        config.ingest_jar_path,
        "--ams.endpoint",
        config.ams_endpoint,
        "--ams.port",
        "443",
        "--ams.token",
        tenant_ams_token,
        "--ams.project",
        tenant_name,
        "--ams.sub",
        "ingest_metric",
        "--hdfs.path",
        f"{config.hdfs_path}/{tenant_name}/mdata",
        "--check.path",
        f"{config.hdfs_path}/{tenant_name}/check",
        "--check.interval",
        "3000",
        "--ams.interval",
        "300",
        "--ams.batch",
        "100",
        "--ams.verify",
        verify,
        "--tenant",
        tenant_name,
    ]

    if dry_run:
        print(("\033[92m" + " ".join(str(x) for x in cmd) + "\033[0m"))
        return 0
    else:
        try:
            subprocess.run(cmd, check=True)
        except Exception as e:
            logger.error(f"Batch Job Error: {e}")
            return 1


def main():
    parser = argparse.ArgumentParser(description="Argo Run Ingest")
    parser.add_argument(
        "-c",
        "--config",
        default="config.yml",
        help="Path to configuration file (default: config.yml)",
    ),
    parser.add_argument(
        "-l",
        "--log-level",
        default="INFO",
        choices=["DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"],
        help="Set logging level (default: INFO)",
    )
    parser.add_argument(
        "-t",
        "--tenant",
        required=True,
        type=str,
        help="select tenant name for computation",
    )
    parser.add_argument(
        "--dry-run",
        help="Runs in test mode without actually submitting the job",
        action="store_true",
        dest="dry_run",
    )
    parser.add_argument(
        "--no-verify",
        action="store_const",
        const="false",
        default="true",
        dest="verify",
        help="Disable verification",
    )

    args = parser.parse_args()

    logging.basicConfig(
        level=getattr(logging, args.log_level),
        format="%(asctime)s - %(levelname)s - %(message)s",
    )

    config = ArgoConfig(args.config)

    if not config.hdfs_path:
        logging.error(
            f"You need to set-up the run.hdfs_path parameter in your configuration file {args.config}"
        )
        return 1

    if not config.ingest_jar_path:
        logging.error(
            f"You need to set-up the run.ingest_jar_path parameter in your configuration file {args.config}"
        )
        return 1

    # check if tenant exists in config
    tenant = config.tenants.get(args.tenant, {})
    if not tenant or not tenant.get("id", {}) or not tenant.get("ams_token"):
        logging.error(f"Tenant {args.tenant} not configured in compute engine")
        return 1

    return run_ingest(
        config, args.tenant, args.dry_run, tenant.get("ams_token"), args.verify
    )


if __name__ == "__main__":
    sys.exit(main())
