#!/usr/bin/env python3

import argparse
import logging
import sys

from init_ingest import run_ingest
from argo_config import ArgoConfig

logger = logging.getLogger(__name__)

def main():
    parser = argparse.ArgumentParser(description="Argo Run Ingest")
    parser.add_argument(
        "-c",
        "--config",
        default="config.yml",
        help="Path to configuration file (default: config.yml)",
    ),
    parser.add_argument(
        "-l",
        "--log-level",
        default="INFO",
        choices=["DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"],
        help="Set logging level (default: INFO)",
    )
    parser.add_argument(
        "-t",
        "--tenant",
        required=True,
        type=str,
        help="select tenant name for computation",
    )
    parser.add_argument(
        "--dry-run",
        help="Runs in test mode without actually submitting the job",
        action="store_true",
        dest="dry_run",
    )
    parser.add_argument(
        "--no-verify",
        action="store_const",
        const="false",
        default="true",
        dest="verify",
        help="Disable verification",
    )

    args = parser.parse_args()

    logging.basicConfig(
        level=getattr(logging, args.log_level),
        format="%(asctime)s - %(levelname)s - %(message)s",
    )

    config = ArgoConfig(args.config)

    if not config.hdfs_path:
        logging.error(
            f"You need to set-up the run.hdfs_path parameter in your configuration file {args.config}"
        )
        return 1

    if not config.ingest_jar_path:
        logging.error(
            f"You need to set-up the run.ingest_jar_path parameter in your configuration file {args.config}"
        )
        return 1

    # check if tenant exists in config
    tenant = config.tenants.get(args.tenant, {})
    if not tenant or not tenant.get("id", {}) or not tenant.get("ams_token"):
        logging.error(f"Tenant {args.tenant} not configured in compute engine")
        return 1

    return run_ingest(
        config, args.tenant, tenant.get("ams_token"), args.dry_run, args.verify
    )


if __name__ == "__main__":
    sys.exit(main())