/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package argo.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class GroupEndpoint extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"GroupEndpoint\",\"namespace\":\"argo.avro\",\"fields\":[{\"name\":\"type\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"group\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"service\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"hostname\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"tags\",\"type\":[\"null\",{\"type\":\"map\",\"values\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"avro.java.string\":\"String\"}]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.String type;
  @Deprecated public java.lang.String group;
  @Deprecated public java.lang.String service;
  @Deprecated public java.lang.String hostname;
  @Deprecated public java.util.Map<java.lang.String,java.lang.String> tags;

  /**
   * Default constructor.
   */
  public GroupEndpoint() {}

  /**
   * All-args constructor.
   */
  public GroupEndpoint(java.lang.String type, java.lang.String group, java.lang.String service, java.lang.String hostname, java.util.Map<java.lang.String,java.lang.String> tags) {
    this.type = type;
    this.group = group;
    this.service = service;
    this.hostname = hostname;
    this.tags = tags;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return type;
    case 1: return group;
    case 2: return service;
    case 3: return hostname;
    case 4: return tags;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: type = (java.lang.String)value$; break;
    case 1: group = (java.lang.String)value$; break;
    case 2: service = (java.lang.String)value$; break;
    case 3: hostname = (java.lang.String)value$; break;
    case 4: tags = (java.util.Map<java.lang.String,java.lang.String>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'type' field.
   */
  public java.lang.String getType() {
    return type;
  }

  /**
   * Sets the value of the 'type' field.
   * @param value the value to set.
   */
  public void setType(java.lang.String value) {
    this.type = value;
  }

  /**
   * Gets the value of the 'group' field.
   */
  public java.lang.String getGroup() {
    return group;
  }

  /**
   * Sets the value of the 'group' field.
   * @param value the value to set.
   */
  public void setGroup(java.lang.String value) {
    this.group = value;
  }

  /**
   * Gets the value of the 'service' field.
   */
  public java.lang.String getService() {
    return service;
  }

  /**
   * Sets the value of the 'service' field.
   * @param value the value to set.
   */
  public void setService(java.lang.String value) {
    this.service = value;
  }

  /**
   * Gets the value of the 'hostname' field.
   */
  public java.lang.String getHostname() {
    return hostname;
  }

  /**
   * Sets the value of the 'hostname' field.
   * @param value the value to set.
   */
  public void setHostname(java.lang.String value) {
    this.hostname = value;
  }

  /**
   * Gets the value of the 'tags' field.
   */
  public java.util.Map<java.lang.String,java.lang.String> getTags() {
    return tags;
  }

  /**
   * Sets the value of the 'tags' field.
   * @param value the value to set.
   */
  public void setTags(java.util.Map<java.lang.String,java.lang.String> value) {
    this.tags = value;
  }

  /** Creates a new GroupEndpoint RecordBuilder */
  public static argo.avro.GroupEndpoint.Builder newBuilder() {
    return new argo.avro.GroupEndpoint.Builder();
  }
  
  /** Creates a new GroupEndpoint RecordBuilder by copying an existing Builder */
  public static argo.avro.GroupEndpoint.Builder newBuilder(argo.avro.GroupEndpoint.Builder other) {
    return new argo.avro.GroupEndpoint.Builder(other);
  }
  
  /** Creates a new GroupEndpoint RecordBuilder by copying an existing GroupEndpoint instance */
  public static argo.avro.GroupEndpoint.Builder newBuilder(argo.avro.GroupEndpoint other) {
    return new argo.avro.GroupEndpoint.Builder(other);
  }
  
  /**
   * RecordBuilder for GroupEndpoint instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<GroupEndpoint>
    implements org.apache.avro.data.RecordBuilder<GroupEndpoint> {

    private java.lang.String type;
    private java.lang.String group;
    private java.lang.String service;
    private java.lang.String hostname;
    private java.util.Map<java.lang.String,java.lang.String> tags;

    /** Creates a new Builder */
    private Builder() {
      super(argo.avro.GroupEndpoint.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(argo.avro.GroupEndpoint.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing GroupEndpoint instance */
    private Builder(argo.avro.GroupEndpoint other) {
            super(argo.avro.GroupEndpoint.SCHEMA$);
      if (isValidValue(fields()[0], other.type)) {
        this.type = data().deepCopy(fields()[0].schema(), other.type);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.group)) {
        this.group = data().deepCopy(fields()[1].schema(), other.group);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.service)) {
        this.service = data().deepCopy(fields()[2].schema(), other.service);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.hostname)) {
        this.hostname = data().deepCopy(fields()[3].schema(), other.hostname);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.tags)) {
        this.tags = data().deepCopy(fields()[4].schema(), other.tags);
        fieldSetFlags()[4] = true;
      }
    }

    /** Gets the value of the 'type' field */
    public java.lang.String getType() {
      return type;
    }
    
    /** Sets the value of the 'type' field */
    public argo.avro.GroupEndpoint.Builder setType(java.lang.String value) {
      validate(fields()[0], value);
      this.type = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'type' field has been set */
    public boolean hasType() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'type' field */
    public argo.avro.GroupEndpoint.Builder clearType() {
      type = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'group' field */
    public java.lang.String getGroup() {
      return group;
    }
    
    /** Sets the value of the 'group' field */
    public argo.avro.GroupEndpoint.Builder setGroup(java.lang.String value) {
      validate(fields()[1], value);
      this.group = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'group' field has been set */
    public boolean hasGroup() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'group' field */
    public argo.avro.GroupEndpoint.Builder clearGroup() {
      group = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'service' field */
    public java.lang.String getService() {
      return service;
    }
    
    /** Sets the value of the 'service' field */
    public argo.avro.GroupEndpoint.Builder setService(java.lang.String value) {
      validate(fields()[2], value);
      this.service = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'service' field has been set */
    public boolean hasService() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'service' field */
    public argo.avro.GroupEndpoint.Builder clearService() {
      service = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'hostname' field */
    public java.lang.String getHostname() {
      return hostname;
    }
    
    /** Sets the value of the 'hostname' field */
    public argo.avro.GroupEndpoint.Builder setHostname(java.lang.String value) {
      validate(fields()[3], value);
      this.hostname = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'hostname' field has been set */
    public boolean hasHostname() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'hostname' field */
    public argo.avro.GroupEndpoint.Builder clearHostname() {
      hostname = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'tags' field */
    public java.util.Map<java.lang.String,java.lang.String> getTags() {
      return tags;
    }
    
    /** Sets the value of the 'tags' field */
    public argo.avro.GroupEndpoint.Builder setTags(java.util.Map<java.lang.String,java.lang.String> value) {
      validate(fields()[4], value);
      this.tags = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'tags' field has been set */
    public boolean hasTags() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'tags' field */
    public argo.avro.GroupEndpoint.Builder clearTags() {
      tags = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    public GroupEndpoint build() {
      try {
        GroupEndpoint record = new GroupEndpoint();
        record.type = fieldSetFlags()[0] ? this.type : (java.lang.String) defaultValue(fields()[0]);
        record.group = fieldSetFlags()[1] ? this.group : (java.lang.String) defaultValue(fields()[1]);
        record.service = fieldSetFlags()[2] ? this.service : (java.lang.String) defaultValue(fields()[2]);
        record.hostname = fieldSetFlags()[3] ? this.hostname : (java.lang.String) defaultValue(fields()[3]);
        record.tags = fieldSetFlags()[4] ? this.tags : (java.util.Map<java.lang.String,java.lang.String>) defaultValue(fields()[4]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
